### ISSUE TITLE
Revisión arquitectura de base de datos para CampusVirtual

### ISSUE THREAD

**Issue by mafeave** [udistrital/campus_cliente#169]
Se debe evaluar la arquitectura de base de datos a tener en cuenta para el proyecto.

**Comment by mafeave** [comment]
En reunión sostenida con @fnrojash y @corio27, se define que para los modelos de datos de los sistemas nuevos, se van a crear 4 bases de datos: ACADEMICA, ADMINISTRATIVA, FINANCIERA y CORE. 

En cada base de datos se creará un esquema para cada microservicio, el cual NO debe contener llaves foráneas a entidades de otro esquema. Cada esquema tendrá su propio usuario para la conexión a la base de datos.

**Comment by JuanPiedrahita** [comment]
Se complementa descripción de esquemas de la base y se agrega api actual de cada uno de los esquemas.

**Comment by mafeave** [comment]
Se generó el siguiente documento: https://docs.google.com/spreadsheets/d/1BzmIRCau1osCBqeI0XoAf5KtZSQvcMyRzoVKE33n-0g/edit?usp=drive_web&ouid=114036767353111235305

Se socializa documento en reunión con arquitectos y DBA el día jueves 23 de mayo.

**Comment by mafeave** [comment]
Se da por finalizada la tarea.
