### ISSUE TITLE
Revisión modelo de datos para producción académica

### ISSUE THREAD

**Issue by mafeave** [udistrital/campus_cliente#170]
Revisar el modelo de datos definido por Planestic para el registro de la información correspondiente a la producción académica, revisar las versiones disponibles en el Drive: https://drive.google.com/drive/folders/1UZsJ7-iNFUyGpd2dLP23vchPxFYfkhHr

**Comment by JuanPiedrahita** [comment]
Se realiza revisión del material entregado. Se tienen los siguientes hallazgos:

- El modelo de producción académica pretende registrar todos los tipos de producciones que se pueden presentar en la universidad, por el momento se tienen definidos los siguientes tipos
    - Articulo
    - Capítulo libro
    - Traducciones
    - Revistas
    - Ponencias
    - LIbros
    - Interpretación
    - Video
    - Cinematográfica
    - Software
    - Adaptación tecnológica
    - Innovación tecnológica
- Se evidencia que cada tipo de producción tiene a su vez subtipos más especificos (Ej.  Articulo de revisión y Articulo aplicado, etc).
- De la versión 1 del modelo: 
    - Este modelo es un modelo general que busca contemplar todos los tipos de publicaciones teniendo en cuenta que para cada uno se deben definir diferentes metadatos por lo cual se hace necesario crear un dato adicional para la producción.
    - El dato adicional no se referencia desde la tabla produccion_academica_dato_adicional.
    - No se contemplan multiples autores para la producción.

- De la versión 2 y 3 del mdelo:
    - Estas versiones del modelo son totalmente diferentes a las planteadas inicialmente y definen esquemas diferentes para cada tipo de producción,  desde el punto de vista este modelo tiene tres problemas:
        1.  El modelo es estatico, es decir, en caso de que aparezca un nuevo tipo de producción que no se pueda contemplar en la tabla otra_publicación  se deberá modificar la base de datos.
        2. El modelo no contempla todos los tipos de producciones especificamente.
        3. El modelo no contempla todos los posibles atributos de cada tipo de producción.

Teniendo en cuenta esto y a la observación de la lider @mafeave sobre la generalización del modelo se llega a las siguientes conclusiones:
- Se debe plantear un modelo como el de la versión 1 que contemple todos los tipos de producciones academicas.
- Se tendra como base el modelo de la versión 1.
- Se subsanarán las observaciones del modelo de la versión 1.
- No se tendrá en cuenta el modelo de la versión 2 y 3 planteados por planestic.

**Comment by JuanPiedrahita** [comment]
Se genera nuevo modelo teniendo en cuentalas observaciones, se tienen los siguientes cambios:
- Se mantienen las tablas:
    - tipo_produccion
    - subtipo_produccion
    - produccion_academica
    - dato_adicional_produccion_academica
    - tipo_dato_adicional

- Se hacen los siguientes ajustes:
    - Se comenta todo el modelo.
    - Se agrega la tabla medio_divulgacion.
    - Se agrega la tabla medio_publicacion.
    - Se cambia longitud del tipo de dato titulo de 24 a 250.
    - Se agrega el campo resumen a la produccion_academica.
    - Se referencia el tipo de dato adicional desde la tabla dato_adiciona_produccion_academica

Quedan las siguientes dudas:
- Uso del campo dominio de tipo json de la tabla tipo_dato_adicional
- Se contamplan multiples autores para una produccion?
- Que otros camos se deberian agregar a la tabla produccion_academica

**Comment by JuanPiedrahita** [comment]
Se realiza revisión con lider @mafeave y se dan las siguientes observaciones:
- Ajustes para realizar al modelo:
    - Cambiar longitud del campo titulo a 500
    - Crear relación entre tabla subtipo_dominio y tipo_dato_adicional de muchos a muchos.
    - Comentar el dato dominio de tipo JSON de la tabla tipo_dato_adicional.
    - Eliminar las tablas medio de divulgación y medio de publicación.
    - Cambiar la bd a core.
- Consideraciones para determinar con DBA y arquitectos:
    - Validar si se usará el concepto de multiples autores, si es usa este concepto se debe definir:
        - Si se refiere a una persona o a un ente.
        - Si se deja la relación con (entidad u organización) en esta tabla puesto que un autor puede pertenecer a otra organización.
        - Si se agrega el campo acepta o no acepta para saber si el autor agregado por otra persona acepta ser autor de la producción.
    - Validar si se debe cambiar el nombre de las tablas que tengan tipo_adicional por algo relacionado con metadato.
    - Validar el papel de la entidad dentro de la producción.

**Comment by JuanPiedrahita** [comment]
Se crea [v5 del modelo de producción academica](https://drive.google.com/drive/folders/1BBHDLl6FC_y9QoArmcZ-3krUVz4sNbJp?usp=sharing) teniendo en cuenta las observaciones planteadas con la lider @mafeave, falta realizar las validaciones correspondientes con el dba y elarquitecto.

**Comment by mafeave** [comment]
Se verifica imagen y archivo en pgmodeler de modelo realizado.

**Comment by fabianbarreto02** [comment]
Se realizan los ajustes sugueridos por el DBA @fnrojash y el arquitecto @jairolh en la reunion realizada el dia 9 de julio, se expone la versión 7 del modelo de datos de eventos.

![produccion_academica](https://user-images.githubusercontent.com/43799065/60906796-a6674000-a23d-11e9-8652-ceb2a20da794.png)

**Comment by fabianbarreto02** [comment]
Se anexa el dbm de modelo propuesto.
[produccion_academica.dbm.zip](https://github.com/udistrital/campus_cliente/files/3374022/produccion_academica.dbm.zip)

**Comment by fabianbarreto02** [comment]
Se realizan los ajustes sugueridos por el DBA @fnrojash y el arquitecto @jairolh en la reunion realizada el dia 11 de julio, se expone la versión 8 del modelo de datos de  produccion academica. Se agregan los campos de activo en todas las tablas para el manejo de los registros activos o no. De igual forma se le agregro a las fk de todas las relaciones _id, para la identificación del id de la tabla referenciada.

![produccion_academicav2](https://user-images.githubusercontent.com/43799065/61095977-6e1d5880-a41b-11e9-8600-aaed4dad78ff.png)

**Comment by fabianbarreto02** [comment]
Se anexa el dbm de modelo propuesto.
[produccion_academicaV2.dbm.zip](https://github.com/udistrital/campus_cliente/files/3384596/produccion_academicaV2.dbm.zip)
