### ISSUE TITLE
Revisión modelo de datos para admisiones

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/campus_cliente#174]
Revisar el modelo de datos definido por Planestic para el registro de la información correspondiente a admisiones, revisar las versiones disponibles en el Drive: 
https://drive.google.com/drive/folders/17UorN10whw5G2KopsRBHr4T9CNoKEiip?usp=sharing

**Comment by JuanPiedrahita** [comment]
Se revisan versiones previas del modelo de admisiones y se hacen las siguientes observaciones:
- Hace falta una tabla para almacenar los documentos soportes de la admisión
- Se incluirán datos demográficos  (Estrato, Salario, Discapacidades, Estado Civil, Cabeza de familia..) del estudiante en el esquema admisiones o estos se gestionan desde otro micro servicio?
- Los descuentos se manejan con el api de descuentos? o se almacena en este modelo datos como si el aspirante ha sido monitor, etc?
- El manejo de los idiomas del aspirante se manejan con el api de idiomas? 
- La formación académica previa se registra en el api de formación_academica?
- Se gestionan los reingresos?
- Se deben separar las propuestas a otro microservicio? Hay que tener en cuenta que una propuesta peude tener varios participantes
- Se deben separar los grupos de investigación y lineas de investigación?  Tener en cuenta que los grupos de investigación tienen categorización por periodos. 
- Se debe tener en cuenta una relación muchos a muchos entre las lineas de investigación y los proyectos curriculaes.
- Se debe mantener el enfasis en este esquema? o en el esquema de proyecto curricular?
- Se debe establecer un tipo de entrevista? para hacer referencia a la de idiomas también
- Se debe tener una relación muchos a muchos entre el criterio de admisión y el proyecto curricular y a a su vez de muchos a muchos entre la admisión y el proyecto curricular y criterio de admisión.

**Comment by JuanPiedrahita** [comment]
Se resuelven dudas con lider tecnica @mafeave:
- Toda la información del aspirante incluyendo soportes se manejan por medio de hoja de vida.
- No tener en cuenta datos demograficos, esto es módulo de matriculas.
- Los descuentos se manejan con el api de descuentos, y van orientados a las matriculas.
- Los idiomas se gestionan, por medio del api de idiomas.
- La información academica se registra en el api de formación academica (Hoja de vida).
- **Desde admisiones se gestionan los reingresos y transferencias. (Dejar datos definidos para transferencias internas, externas y reingresoos, estos estan sujetos a cambios debido a levantamiento de requerimientos)**
- **Dejar la propuesta en el mismo esquema y el tipo de proyecto se consume desde otro esquema**
- **Propuesta individual.**
- **Plantear esquema para grupos de investigacion**
- SE referencia el ccriterio de admisión de idioma.
- **Se debe tener una relación muchos a muchos entre el criterio de admisión y el proyecto curricular y a a su vez de muchos a muchos entre la admisión y el proyecto curricular y criterio de admisión.**

**Comment by JuanPiedrahita** [comment]
Se genera [propuesta del modelo de admisiones](https://drive.google.com/drive/folders/1uIAI8LfF51TcbIommrKDmuFc0juQjobp?usp=sharing) y se establecen las siguientes dudas:
- Se debe almacenar la fecha en la que el aspirante acepta terminos
- La propuesta puede tener varias lineas de investigacion? 
- La propuesta puede tener un estado como avalada, no avalada etc., o con flag de activo?
- Se almacenaran comentarios sobre la propuesta?
- Se sube algún documento relacionado con la propuesta?
- Se deben almacenar justificación o comentarios sobre la entrevista?
- se pueden contemplar multiples entrevistadores?
- el periodo academico  debe relacionarse de otro esquema a la tabla criterio o se dejará un activo?

- Se debe validar con campus información para transferencias y reintegros

**Comment by JuanPiedrahita** [comment]
SE asiste a reunión con Planestic donde se define lo siguiente:
- El modelo de grupo_investigacion se trabajará como microservicio por parte del CIDC asi que no se tendra en cuenta.
- Puede almacenar se la fecha en la que los estudiantes aceptan los terminos.
- La propuesta no tiene varias lineas de investigación.
- La propeusta no tiene un estado, solamente es un requisito para la entrada.
- NO se almacenará una retroalimentación sobre la propuesta. 
- Se sube un documento asociado a la propuesta que en este caso y para la v6 esta referido con el atributo formato_proyecto puesto que es un formato del proyecto curricular.
- No se almacena justificación sobre una entrevista.
- Por el modelo de negocio se pueden tener en cuenta multiples entrevistadores.
- El periodo academico se referencia desde otro esquema (Pendiente por definir el esquema).
- Se deben mantener las tablas de transferencias y reintegros (Información de las tablas pendiente por levantamiento de requerimientos).


Se deben hacer los ajustes necesarios al modelo de datos y se debe tener en cuenta que el modelo esta sujeto a cambios debido a que no se ha hecho el levantamiento de requerimientos.

**Comment by JuanPiedrahita** [comment]
Se corrige modelo con las observaciones dadas, se actualiza el [modelo ](https://drive.google.com/drive/folders/1uIAI8LfF51TcbIommrKDmuFc0juQjobp?usp=sharing) y se espera el levantamiento de requerimientos para refinar el modelo.

**Comment by mafeave** [comment]
Se revisa carga de imagen del modelo y de archivo en pgmodeler. Se da por terminada la tarea, tener en cuenta que no se ha levantado el análisis del módulo, por lo cual es probable que se generen cambios a futuro.
