### ISSUE TITLE
Revisión para acoplar modelo de admisiones a pregrado

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/campus_cliente#175]
Revisión del desarrollo de los modelos de datos de admisiones, para acoplar a pregrado. Consultar el instructivo: https://www.udistrital.edu.co/instructivo-admisiones

**Comment by JuanPiedrahita** [comment]
Se inicia revisión de los 7 pasos del instructivo de admisión en el siguiente [documento](https://docs.google.com/document/d/1Xn0Cu2kVcuwv8213rzkGAMq5buKoL9_285q_BaCMvKo/edit?usp=sharing).

**Comment by JuanPiedrahita** [comment]
Se hace revisión del primer paso.

**Comment by JuanPiedrahita** [comment]
Se agregan consideraciones generales en el documento.

**Comment by JuanPiedrahita** [comment]
Se realiza revisión de los pasos restantes.

**Comment by JuanPiedrahita** [comment]
Se realiza resumen, ***por favor tener en cuenta que se necesita información de levantamiento de requerimientos para poder completar los modelos***:
Falta para acoplar el modelo (Resumen, en caso de querer más especificidad leer todo el documento):
- Definir donde se almacenan los términos y condiciones.
- Definir donde se almacenan los términos y condiciones.
- Tablas paramétricas para reglas de negocio:
    - Inhabilidades.
    - Vigencias del icfes.
    - Definir esquema para criterios de admisión.
    - Cupos aprobados por proyecto por periodo.
- Requisitos adicionales: 
    - Documentos adicionales para la admisión (Definir donde se guardaran). Ejm: Títulos convalidados.
- Definir donde se guardaran los resultados de las pruebas específicas
- Información de cupos especiales.
- Información de Generación E.
- Almacenar SNP del examen del icfes (Definir en donde).
- Almacenar información para la liquidación (Definir donde).
- Información para REINGRESOS, TRANSFERENCIAS y CICLOS PROPEDÉUTICOS.
- Costo de la inscripción por periodo (Definir donde se almacena).
- Si se automatiza el proceso de selección se debe tener en cuenta que se deben almacenar los resultados del proceso.
    - Posición.
    - Puntaje total.
    - Cambio de estado de la admisión.
- Tener definidos modelos y apis de:
    - Proyecto Curricular.
    - Hoja de Vida.
    - Formación Académica
    - Idiomas
    - Tablas de periodo académico.
    - Sesiones o Eventos

**Comment by mafeave** [comment]
Se revisa el análisis realizado de acuerdo al instructivo de admisiones, se comparte con el analista @FaustoPuerto para realizar una priorización de los requerimientos. 

Se da por finalizada la tarea.
