### ISSUE TITLE
Integración del modelo de datos de proyecto curricular con Oikos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/campus_cliente#178]
Revisión del modelo de datos para del proyecto curricular de oikos para la integración del sistema de gestión academica, se debe realizar:

- [x] Detallar que tablas son necesarias para la integración a sistema de gestión academica.
- [x] Definir Nuavas tablas si es necesario para integración a el sistema de gestión academica.
- [x] Concluir si el modelo es viable para la integración a el sistema de gestión academica

Se tiene en cuenta la siguiente documentación:
- [OIKOS Modelo Base](https://drive.google.com/drive/folders/13nXiYsP2rFxfEHMLmRAZ4bxZNh185gkB)
- [programas académicos - titulaciones V5](https://drive.google.com/drive/folders/1gUzjOIZvUTchVtBy4aJBsk7Om_U7SQXt)

**Comment by fabianbarreto02** [comment]
Se inicia revisión del modelo de OIKOS [https://drive.google.com/drive/folders/13nXiYsP2rFxfEHMLmRAZ4bxZNh185gkB](MODELO)

**Comment by fabianbarreto02** [comment]
Se inicia documento de Análisis del modelo de datos de OIKO [https://docs.google.com/document/d/1BJj4inivoJ3o_syS2U3YKPsKbHpL0L6vCjj5zobqioo/edit?usp=sharing](Documento)

**Comment by fabianbarreto02** [comment]
Despues del analisis del modelo de datos del Sistema OIKOS, y despues de realizar unos ajustes del modelo se suguiere el siguiente modelo, el cual tambien se suguiere la siguiente integracion del modelo de datos programa academico

![Migracion_OIKO](https://user-images.githubusercontent.com/43799065/59129551-c5b73880-8932-11e9-9c0e-f82b6086e187.png)

**Comment by fabianbarreto02** [comment]
Se anexa el dbm del modelo de datos desarrollado en pgModeler versión 0.9.1

[Migracion_OIKOS.dbm.zip](https://github.com/udistrital/campus_cliente/files/3267370/Migracion_OIKOS.dbm.zip)

**Comment by fabianbarreto02** [comment]
Carpeta donde se encuentra todo el analisis echo [Documentación](https://drive.google.com/drive/folders/1OJll6E_VNLYEyRyreTpUgqrfhbQ2791l)

**Comment by fabianbarreto02** [comment]
Se da por finalizado la documentación del analisis

**Comment by mafeave** [comment]
Tener en cuenta que los campos referenciados de las relaciones de 1 a *, debe quedar con el nombre de la tabla referenciada, sin que se anteponga 'id_'

**Comment by fabianbarreto02** [comment]
Se corrugué las referencias en las relaciones 1 a *

**Comment by mafeave** [comment]
Se verifica archivo en pgmodeler, imagen del modelo y análisis de los esquemas revisados.

**Comment by fabianbarreto02** [comment]
Se actualizan .dbm y la imagen del modelo de datos, se corrige los nombres de las referencias dependencias en la tabla programas_academicos_institucion y la referencia enfasis en la tabla institucion_enfasis
