### ISSUE TITLE
Modificación de cliente de campus para manejar nuevo modelo de producción academica

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/campus_cliente#184]
Modificación del cliente teniendo en cuenta el nuevo modelo de producción academica.

**Comment by JuanPiedrahita** [comment]
Se agrega docker compose para desarrollo https://github.com/udistrital/campus_cliente/commit/34aaa0c57f9e6f51e1b60771f760038592db7b38

**Comment by JuanPiedrahita** [comment]
SE agrega modulo  de produccion academica https://github.com/udistrital/campus_cliente/commit/ce3b44f3d7fac2f120954269501522b98136b779

**Comment by JuanPiedrahita** [comment]
Selección de parametros iniciales de la producción 
https://github.com/udistrital/campus_cliente/commit/3b49eeee9df8829f18d10a23dbd3f2bd5c71709d
https://github.com/udistrital/campus_cliente/commit/cccf52666a3ebedd9233bdb4fa9f5265b3d0b625

**Comment by JuanPiedrahita** [comment]
SE carga formulario con dynamic form
https://github.com/udistrital/campus_cliente/commit/ce55a569d32f619da87fa3808bd6f95a724ecbf7
https://github.com/udistrital/campus_cliente/commit/1bc87c1862ed7ba73a02559f8c33f413e7f775a2

**Comment by JuanPiedrahita** [comment]
SE permite registrar una producción academica
https://github.com/udistrital/campus_cliente/commit/6c049779e92606b7ba2e3f2edb68c433c4923454
https://github.com/udistrital/campus_cliente/commit/e86e765ccc7f5475acd928ebbcd9e1bcabdacfaf

**Comment by JuanPiedrahita** [comment]
Se listan producciones
https://github.com/udistrital/campus_cliente/commit/5f020b3d5173a2128afceff4541377188a719a18

**Comment by JuanPiedrahita** [comment]
SE borran producciones 
https://github.com/udistrital/campus_cliente/commit/3adb04ad5762cb7a59e80d3e41eb373fa4a0fe1e

**Comment by JuanPiedrahita** [comment]
Se permite editar la producción
https://github.com/udistrital/campus_cliente/commit/ab23181ca6d410f2be77a79373e5decbde71b675
https://github.com/udistrital/campus_cliente/commit/d25e2955e3439de427d1d1dbb562159dae88bb0c

**Comment by JuanPiedrahita** [comment]
Se agregan los estados del autor y se permite editarlos 
https://github.com/udistrital/campus_cliente/commit/768021be1c8155f671113cd61b40bc45a6b8488c
https://github.com/udistrital/campus_cliente/commit/e5e2ca6e4c283736eb5ba9eee3a5ac02dda08d0b

**Comment by mafeave** [comment]
Se verifican los commits del desarrollo realizado.
