### ISSUE TITLE
Proponer un modelo de datos para el tipo de viculación de una persona

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/campus_cliente#185]
Se debe proponer un modelo de datos en el cual se especifique el tipo vinculación que tiene una persona con la oraganización. Se debe tener encuenta los siguientes especificaciones:

- [x] Se debe sugerir en qué esquema debe incorporarse el modelo de datos.
- [x] Realizar la documentación necesaria para la propuesta del modelo de datos.
- [x] El modelo de datos debe contar con los lineamientos definidos por la OAS.

Lider técnico: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de diseño

**Comment by fabianbarreto02** [comment]
Como propuesta del modelo de datos para el tipo de vinculación de una persona se establece el siguiente modelo.

![Captura de Pantalla 2019-06-18 a la(s) 3 30 17 p  m](https://user-images.githubusercontent.com/43799065/59776868-2ae72400-9279-11e9-8cbf-0c810683c580.png)

**Comment by fabianbarreto02** [comment]
Durante el desarrollo del modelo, se suguiere que el modelo diseñado se integre en el modelo de datos de persona, esta suguerencia tiene que ser evaluada por el equipo de core, pues el que administra este modelo, la siguiente imagen muestra la sugerencia realizada.

![Prupuesta_persona_con_relacion_cargo_universidad](https://user-images.githubusercontent.com/43799065/59777492-659d8c00-927a-11e9-9c77-cedb2f660860.png)

**Comment by fabianbarreto02** [comment]
Finalmente se realiza un documento donde se específica el modelo propuesto.

[Documento](https://docs.google.com/document/d/1eVsRjlN8bIji0Us15Ke_40rbXiSJfdAZaHY8EON-z4c/edit)

**Comment by mafeave** [comment]
Se socializará la necesidad de guardar la relación de persona con las dependencias al grupo del CORE con el modelo propuesto.

**Comment by fabianbarreto02** [comment]
Se agrega un campo en la tabla de rompimiento que relaciona la dependencia con la que esta vinculada la persona  (proyecto curricular )

**Comment by fabianbarreto02** [comment]
Se anexa el dbm propuesto.

[Prupuesta_persona_con_relacion_cargo_universidad.dbm.zip](https://github.com/udistrital/campus_cliente/files/3325832/Prupuesta_persona_con_relacion_cargo_universidad.dbm.zip)
