### ISSUE TITLE
Revisión de OIKOS y proyectos curriculares para la posterior migración de data

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/campus_cliente#186]
Se requiere poder consultar los proyectos curriculares actuales en la universidad por medio del sistema oikos. La issues debe tener encuenta los siguientes requerimientos:

- [x] Revisar y consultar si el servicio de OIKOS contiene los proyectos curriculares actuales en la universidad.
- [x] Establecer si los proyectos curriculares tiene relacionados el codigo SNIES del ministerio de edución.
- [x] Establecer como hacer la peticion de los proyectos curriculales registrados en OIKOS.

Lider Técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de análisis

**Comment by fabianbarreto02** [comment]
En una revisión del sistema OIKOS con acompañamiento de @mafeave y @corio27, se determina, que  el sistema OIKOS cuenta con los proyectos curriculares actuales y avalados por el Sistema Nacional de Información de la Educación Superior, se realiza la revision del cliente de OIKOS en la dirección de pruebas [10.20.0.254/oikos](10.20.0.254/oikos), donde se observa la data del sistema.

**Comment by fabianbarreto02** [comment]
En cuanto a la relacion de los codigos SNIES dados por el El Sistema Nacional de Información de la Educación Superior, y los proyectos curriculares, el sistema de OIKOS, cuenta con una tabla temporal que relaciona los id de la siguiente forma:


|      Id          |Id SNIES (Código)                  |Id gd| Id ARKA|
|----------------|-------------------------------|------------------------|------------------------|  


Se tiene que tener en cuenta que el sistemas OIKOS solo contiene la informacio de nombre,telefono y correo electronico, La información paramétrica  dada por el SNIES como metodologia, titulacion, nivel_formacion y enfasis no se encuentra contemplada en el sistemas de OIKOS

**Comment by fabianbarreto02** [comment]
Finalmente para realizar la petición de los proyectos curriculares al servicio de OIKOS se debe realizar la siguiente petición:

Para acceder a la informacion de todos los proyectos curriculares (pregrados y posgrados) se debe realizar de la siguiente forma:

10.20.0.254/oikos_api/v1/dependencia_tipo_dependencia/?query=TipoDependenciaId:1&limit=0

TipoDependenciaId:1 

Para acceder a la informacion de proyectos curriculares solo de pregrado:

TipoDependenciaId:14

Finalmente para acceder a proyectos curriculares de posgrado:

TipoDependenciaId:15

**Comment by fabianbarreto02** [comment]
Queda pendiente revisión por parte de @mafeave lider técnica

**Comment by mafeave** [comment]
Verificada la tarea. Se informa al grupo de Planestic para que consuman la información correspondiente a los programas académicos desde OIKOS.
