### ISSUE TITLE
Diseñar el modelo de la arquitectura de la información (actividad planeada a una semana y media)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/campus_cliente#187]
Se debe Diseñar el modelo de la arquitectura de la información para los modulos de Inscripción y admision del sistema de gestión academica. El diseño debe cumplir con los siguientes requerimientos:

- [x] Establecer cual es la información util, usable, deseable, entregable, creible y valiosa.
- [x] Definir los usuarios.
- [x] Diseñar la arquitectura de la información con la herramienta Archimate.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de diseño

**Comment by fabianbarreto02** [comment]
La definición de la información util, usable, deseable, entregable, creible y valiosa para los modulos de inscripción y admisión se establecen en:

- admision
- estado_admision
- propuesta
- transferencia
- reintegro
- criterio_admision
- criterio_programa_academico
- criterio
- entrevista
- entrevistador
- tipo_entrevista
- estado_entrevista
- trabajo_grado
- programa_academico_institucion
- metodologia
- titulacion
- nivel_formacion
- enfasis

**Comment by fabianbarreto02** [comment]
La definición de los usuarios para la arquitectura de la información de los modulos de inscripción y admisión son:

- Aspirantes
- Administradores del proceso de inscripción.
- Administradores del proceso de admisión.
- Proyectos curriculares.

**Comment by fabianbarreto02** [comment]
Como arquitectura de la información para los modulos de Inscripción y admisión del sistema de gestión académica se propone la siguiente arquitectura:

![Arquitectura de la información modulos inscripción y admisión](https://user-images.githubusercontent.com/43799065/60208892-09f57480-981f-11e9-857f-76ecd9d95057.png)

**Comment by fabianbarreto02** [comment]
El archivo fuente de la arquitectura de la información se desarrollo en la herramenta draw.io, herramienta gratuita y en linea sugerida por la oficina de asesora de sistemas, el archivo se puede encontrar en el[enlace](https://drive.google.com/drive/folders/1Ffrz5Pu5WgrdxZV_PAv1sPduikN-xXKr)

**Comment by fabianbarreto02** [comment]
Queda pendiente de revisión por la lider técnica @mafeave

**Comment by mafeave** [comment]
Observaciones:
- Falta la representaciòn de los formularios de registro de hoja de vida
- Agregar la información en los objetos que dice (Por definir)
- Cambiar nombre de admision por inscripcion

Está pendiente la validación del modelo junto a algunos de los arquitectos. Por otra parte, el modelo debería estar en archi no en draw.io

**Comment by fabianbarreto02** [comment]
Se realizar la correción de las observaciones realizadas por @mafeave, se anexa la nueva arquitectura.

![Arquitectura_de_la_información_modulos_inscripción_y_admisión](https://user-images.githubusercontent.com/43799065/60532165-4c58fe80-9cc2-11e9-8f24-433a8e0ece69.png)

**Comment by fabianbarreto02** [comment]
Finalmente se exporta la arquitectura al software ARCHI, se anexa el archivo fuente, para revisión de nuevo por el lider técnico: @mafeave.

[Arquitectura de la información modulos inscripción y admisión.archimate.zip](https://github.com/udistrital/campus_cliente/files/3351188/Arquitectura.de.la.informacion.modulos.inscripcion.y.admision.archimate.zip)

**Comment by mafeave** [comment]
Se verifica realización de los ajustes solicitados
