### ISSUE TITLE
Definir modelo de datos del periodo académico

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/campus_cliente#188]
Se debe definir cual modelo de datos se debe utilizar para el manejo del periodo de académico, revisar en que esquema se debe ubicar el modelo para su consumo.

**Comment by fabianbarreto02** [comment]
Se inicio el proceso de definición.

**Comment by fabianbarreto02** [comment]
En reuniones realizadas con el equipo de desarrollo del core, lider de proyecto Diana Ramirez y lider técnica @mafeave  se establece que este modelo de datos es transversal a varios sistema de la oficina y se sugiere que el grupo de core realice el diseño y el despliegue del api, sin embargo, teniendo en cuenta un diseño del modelo de [sesiones](https://drive.google.com/drive/folders/1Vvw-HUAcnRHeOcxoarp6Y09PMZ6Cg9_b), se realiza el analisis y se establece que el modelo   es viable para el modelo de datos del periodo academico, se espera que los dba y arquitectos revisen el modelo.

**Comment by fabianbarreto02** [comment]
Se realizan los ajustes sugueridos por el DBA @fnrojash y el arquitecto @jairolh en la reunion realizada el dia 9 de julio, se expone la versión 2 del modelo de datos de eventos. Se crea una tabla tipo periodo para el manejo de los distintos periodos que pueden existir, como academico, ilud, extensión entre otros, se agregan los campos de fecha de creación y fecha de modificación en todas las tablas del modelo propuesto.

![Captura de Pantalla 2019-07-09 a la(s) 11 55 00 a  m](https://user-images.githubusercontent.com/43799065/60909028-d1a05e00-a242-11e9-9aca-36949e4c7db5.png)

**Comment by fabianbarreto02** [comment]
Se realizan los ajustes sugueridos por el DBA @fnrojash y el arquitecto @jairolh en la reunion realizada el dia 9 de julio, se expone la versión 2 del modelo de datos de periodo academico (ahora solo peridod). Se crea una tabla tipo periodo para el manejo de los distintos periodos que pueden existir, como academico, ilud, extensión entre otros, se agregan los campos de fecha de creación y fecha de modificación en todas las tablas del modelo propuesto.

![Captura de Pantalla 2019-07-11 a la(s) 8 40 01 p  m](https://user-images.githubusercontent.com/43799065/61096180-47135680-a41c-11e9-8c96-ea402177db35.png)

**Comment by mafeave** [comment]
Se verifica modelo ajustado, se da por finalizada la tarea
