### ISSUE TITLE
Ajustes de API`s incripción y evaluación inscripcion por revisión de DBA y arquitecto.

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/campus_cliente#190]
Se deben ajustar lo modelos de datos para admision(ahora inscripcion) y calificacion admision (ahora evaluacion inscripcion), posteriormente se debe ajustar las API´s ya desarrolladas, los API´s deben cumplir con los siguientes requerimientos:

- [x] El crud debe cumplir con los lineamientos de la Oficina asesora de sistemas.
- [x] El crud debe contar con el refactor, para que las respuestas sean en formato Json.
- [x] Comprobar si la Api funciona correctamente con Swagger.  

Lider técnica : @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo en el repositorio [evaluacion_inscripcion](https://github.com/udistrital/evaluacion_inscripcion_crud) en la rama modelov8

**Comment by fabianbarreto02** [comment]
Se realiza el proceso de ajustar el modelo de datos de evaluacion_inscripcion(antes calificacion_admision), se anexa la figura para observar el modelo.

![evaluacion_admision](https://user-images.githubusercontent.com/43799065/60375924-3f41c400-99d1-11e9-9874-f83f2792215a.png)

**Comment by fabianbarreto02** [comment]
Se termina el la actualización del api evaluación inscripcion, este esta en la RAMA modelov8, se espera revisión de la lider técnica @mafeave.

**Comment by fabianbarreto02** [comment]
Se realiza el proceso de ajustar el modelo de datos de inscripcion(antes admision), se anexa la figura para observar el modelo.

![inscripcion](https://user-images.githubusercontent.com/43799065/60377446-baf53e00-99dc-11e9-99f7-bbb64759cb44.png)

**Comment by fabianbarreto02** [comment]
La caperta donde se encuantra los archivos fuentes de los dos modelo ajustados se encuentra [enlace](https://drive.google.com/drive/folders/1VAGv4h5qiUSwbgXJHhuCACInf51xqo4k) en la ultima versión.

**Comment by fabianbarreto02** [comment]
Se termina  la actualización del api  inscripcion, este esta en la RAMA modelov8, se espera revisión de la lider técnica @mafeave. El repositorio se puede observar en [admisiones](https://github.com/udistrital/evaluacion_inscripcion_crud/tree/modelov8)

**Comment by mafeave** [comment]
Se verifican los commits realizados en las APIs de inscripcion y calificacion_inscripcion
