### ISSUE TITLE
Definir modelo de datos eventos

### ISSUE THREAD

**Issue by mafeave** [udistrital/campus_cliente#191]
Definir modelo de datos eventos (Fechas del proceso de inscripción).

**Comment by JuanPiedrahita** [comment]
Se define y comparte [modelo propuesta](https://drive.google.com/drive/folders/1rgNK8AOcxQpEngYQ7xarebuwrDxf3TAU?usp=sharing) de eventos con crontabs.

**Comment by fabianbarreto02** [comment]
Se ajusta el modelo propuesto para el manejo de [eventos](https://drive.google.com/drive/folders/1Vvw-HUAcnRHeOcxoarp6Y09PMZ6Cg9_b)

**Comment by fabianbarreto02** [comment]
Se realiza una version dos para el modelo de eventos donde se contemplan los atributos de los tipo de evento, ejemplo: generación E, reintegro, etc para el evento de inscripción, el modelo se muestra en [evento Version 2](https://drive.google.com/drive/folders/1M5EChCuRDmOnR9z_-BRa1wDGWqCCg336).

**Comment by fabianbarreto02** [comment]
Se realizan los ajustes sugueridos por el DBA @fnrojash y el arquitecto @jairolh en la reunion realizada el dia 8 de julio, se expone la versión 3 del modelo de datos de eventos.

![eventoV3](https://user-images.githubusercontent.com/43799065/60837009-c559c980-a18c-11e9-97c9-2201c548603d.png)

**Comment by fabianbarreto02** [comment]
Se anexa el dbm de modelo propuesto.
[eventoV3.dbm.zip](https://github.com/udistrital/campus_cliente/files/3369940/eventoV3.dbm.zip)

**Comment by fabianbarreto02** [comment]
Se realizan los ajustes sugueridos por el DBA @fnrojash y el arquitecto @jairolh en la reunion realizada el dia 9 de julio, se expone la versión 4 del modelo de datos de eventos.

![eventoV4](https://user-images.githubusercontent.com/43799065/60906564-07dadf00-a23d-11e9-98cf-b95040592168.png)

**Comment by fabianbarreto02** [comment]
Se anexa el dbm de modelo propuesto.
[eventoV4.dbm.zip](https://github.com/udistrital/campus_cliente/files/3373968/eventoV4.dbm.zip)

**Comment by mafeave** [comment]
Se verifica la realización de los ajustes de acuerdo a las observaciones dadas por el DBA y el arquitecto.

**Comment by fabianbarreto02** [comment]
Se realizan los ajustes sugueridos por el DBA @fnrojash y el arquitecto @jairolh en la reunion realizada el dia 11 de julio, se expone la versión 5 del modelo de datos de eventos. Se agregó el posible modelo, tiene una tabla para métrica nueva para el tipo de público que se dirige a el evento y las excepciones se manejaría como  un tipo de evento.

![eventoV7](https://user-images.githubusercontent.com/43799065/61218310-5f62ca00-a6d7-11e9-8d80-30b2f4e18f20.png)

**Comment by fabianbarreto02** [comment]
Se anexa el dbm de modelo propuesto.
[eventoV7.dbm.zip](https://github.com/udistrital/campus_cliente/files/3392398/eventoV7.dbm.zip)

**Comment by fabianbarreto02** [comment]
Se realizan los ajustes sugueridos por el DBA @fnrojash y el arquitecto @jairolh en la reunion realizada el dia 17 de julio, se expone la versión 7 del modelo de datos de eventos. Se corregue el nombre las llaves foraneas donde se tenia la palabra sesiones, se corriguen los nombres de los campo donde se refencian a otros esquemas agregando el subfijo _id, adicionalmente se acada la sugerencia de agregar notas para aclarar a que esquema y sistema referencian esos campos. Se expone la siguiente figura del modelo de datos con las correciones correspondientes.

![eventoV8](https://user-images.githubusercontent.com/43799065/61467097-ab647780-a940-11e9-84c2-f7ee8a745273.png)

**Comment by fabianbarreto02** [comment]
Se anexa el dbm de modelo propuesto.
[eventoV8.dbm.zip](https://github.com/udistrital/campus_cliente/files/3407049/eventoV8.dbm.zip)

**Comment by mafeave** [comment]
Modelo anexado en el kanban de revisión con el arquitecto y DBA, ver[ kanban N° 31216](https://tuleap.udistrital.edu.co/plugins/tracker/?aid=31216)
