### ISSUE TITLE
Crear API para el modelo de periodo academico

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/campus_cliente#192]
Creación del CRUD para el modelo de datos del esquema periodo academico establecido en el [modelo](https://drive.google.com/drive/folders/1Vvw-HUAcnRHeOcxoarp6Y09PMZ6Cg9_b), el API debe cumplir con los siguientes requerimientos:

- [x] El crud debe cumplir con los lineamientos de la Oficina asesora de sistemas.
- [x] El crud debe contar con el refactor, para que las respuestas sean en formato Json.
- [x] Comprobar si la Api funciona correctamente con Swagger.

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo del API para el modelo de datos de periodo academico

**Comment by fabianbarreto02** [comment]
Se realiza el api crud utilizando como base el api desarrollado por el equipo del core, se realiza los ajustes para las respuestas en formato json el [repositorio](https://github.com/udistrital/core_crud/tree/periodo_academico) donde se desarrollo es el mismo del core pero en la rama llamada periodo_academico.

Se espera revisión por parte de la lider técnica @mafeave.

**Comment by mafeave** [comment]
Se verifica agregación de modelo y controlador de programa_academico al API del Core, se debe ajustar el nombre de acuerdo a la observación dada en la reunión de revisión de modelos.

**Comment by fabianbarreto02** [comment]
Se corrige los nombres como se acordo en la reunion con dba y arquitecto.

**Comment by fabianbarreto02** [comment]
Se realiza el ajuste del api, donde se incluye las modificaciones sugueridos por el DBA @fnrojash y el arquitecto @jairolh en la reunion realizada el dia 9 de julio, la api es desarrollada en  la rama periodo academico en el repositorio core crud , [Repositorio](https://github.com/udistrital/core_crud/tree/periodo_academico). queda pendiente revisión por parte de la lider técnica @mafeave.

**Comment by fabianbarreto02** [comment]
Se realiza el ajuste del api, donde se incluye las modificaciones sugueridos por el DBA @fnrojash y el arquitecto @jairolh en la reunion realizada el dia 11 de julio, la api es desarrollada en  la rama periodo academico en el repositorio core crud , [Repositorio](https://github.com/udistrital/core_crud/tree/periodo_academico). Se cambia el campo nombre del modelo periodo y se agregan campos año y periodo, queda pendiente revisión por parte de la lider técnica @mafeave.

**Comment by mafeave** [comment]
Se verifican los ajustes en el API, se da por finalizada la tarea.
