### ISSUE TITLE
Ajustar el api de core_crud con la tabla de conceptos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/campus_cliente#194]
Ajuste del CRUD para el modelo de datos del esquema conceptos establecido en el [modelo](https://drive.google.com/drive/folders/1oHPdamuQ1XukHKz34DrqVioziOlUe9hF), el API debe cumplir con los siguientes requerimientos:

- [x] El crud debe cumplir con los lineamientos de la Oficina asesora de sistemas.
- [x] El crud debe contar con el refactor, para que las respuestas sean en formato Json.
- [x] Comprobar si la Api funciona correctamente con Swagger.

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se agrega los modelos, controladores y rutas necesaria para ajustar el api core_crud con la tabla nueva de conceptos_academicos, necesaria para el modelo de datos de descuentos.

**Comment by fabianbarreto02** [comment]
El modelo de datos con el que se trabajo el api se expone en la siguien imagen.

![core](https://user-images.githubusercontent.com/43799065/61475565-b2938180-a950-11e9-9630-7f553b031729.png)

**Comment by fabianbarreto02** [comment]
Se anexa el dbm.
[core.dbm.zip](https://github.com/udistrital/campus_cliente/files/3407503/core.dbm.zip)

**Comment by fabianbarreto02** [comment]
El api ajustado se encuentra desarrollada en la rama concepto_academico del [repositorio](https://github.com/udistrital/core_crud/tree/concepto_academico) core_crud, se espera la revisión por parte de la lider técnica: @mafeave .

**Comment by mafeave** [comment]
Se revisan los ajustes realizados en el API, ajustar lo siguiente:
- eliminar el archivo main_test.go

**Comment by fabianbarreto02** [comment]
Se realiza el ajuste de eliminar el archivo main_test.go por sugerencia por parte de la lider tecnica

**Comment by mafeave** [comment]
Ajustada la oservaciòn se da por finalizada la tarea.
