### ISSUE TITLE
Desarrollo cliente para activar el periodo

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/campus_cliente#195]
Se debe desarrollar el cliente para la funcionalidad de activar y desactivar el periodo academico, en listar los antiguios y crear nuevos periodos adicionalmente debe permiter crear el tipo de perido, el modelo de datos de cual se parte se define en el siguiente [link](https://drive.google.com/drive/folders/1VJ_90KilPyiXfc7_INvaadbkbXQXyEkf), el cliente debe cumplir con los siguientes requerimientos:

- [x] El cliente debe desarrollarse en componentes para su facil integración en el sistema.
- [x] Cumplir con el objetivo del modulo: "Permite definir el periodo académico que se va a dejar disponible para el proceso de inscripciones y admisiones, e igualmente permite observar los últimos períodos registrados en el sistema." 
- [x] Debe registrar los campos de fecha creación y fecha modificación de forma automatica, oculata del usuario.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
El cliente se desarrolla en la [rama](https://github.com/udistrital/campus_cliente/tree/habilitar_periodo) habilitar_periodo del repositorio campus_cliente, queda pendiente la revisión por parte de la lider técnica @mafeave .

**Comment by mafeave** [comment]
Se verifica el commit realizado para la funcionalidad de habilitar el periodo académico.
