### ISSUE TITLE
Revisión modelo de recibos de pago de Planestic

### ISSUE THREAD

**Issue by mafeave** [udistrital/campus_cliente#196]
Revisar modelo de datos propuesto por parte de Planestic con los arquitectos y DBAs

**Comment by mafeave** [comment]
Se solicita a @jevilla94 el modelo creado para la revisión por parte interna de los arquitectos y DBAs de la OAS

**Comment by mafeave** [comment]
Se anexa modelo enviado por @jevilla94 
![image](https://user-images.githubusercontent.com/14035745/61810303-a00fc100-ae04-11e9-8f4b-72498445a278.png)

**Comment by mafeave** [comment]
De acuerdo con @jevilla94 , el modelo de recibos de pago se propone por lo siguiente:
1. control de recibos generados por el campus
2. como hay unos aspirantes que no pagarían virtualmente, se maneja el campo de comprobante que sería el documento de la consignación escaneada
3. verificación de estado del recibo para cambio de estado en el aspirante

**Comment by mafeave** [comment]
Revisar la creación de servicios web que permitan consultar los siguiente:
- Consulta del recibo
- Estado del pago
- Tipo de pago de los recibos
Se deben tener en cuenta para el cambio de estado de la inscripción y el registro en el servicio web de pagos se deben tener ya creados los servicios web.

Para el comprobante de consignación se debe dejar una tabla similar a la tabla pago_recibo, revisar el flujo de verificación de las consignaciones, verificar con admisiones y tesorería.

**Comment by mafeave** [comment]
el campo de referencia solo se ingresaria cuando se tiene un registro en académica

**Comment by jairolh** [comment]
- Actualmente la gestión de recibos de pago la realiza sistema de gestión academica y para consultar la información del recibo, se deberia solicitar la generación de los servicios web para consultar dicha información.

- Para pagos de inscripciones por ventanillas el módelo no aplica, ya que dichos esos pagos no generan un recibo de pago en el sistema. Por tanto una solución propuesta es que se adicione a los datos de inscripción el codigo de referencia generado en la transacción.
