### ISSUE TITLE
Formulario de consulta de la oferta académica

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/campus_cliente#199]
Se debe desarrollar el cliente para la funcionalidad de en listar la oferta academica que se encuentran activas para el periodo(Año y periodo) activo,  debe consumir el servicio del mid, el cliente debe cumplir con los siguientes requerimientos:

- [x] El cliente debe desarrollarse en componentes para su facil integración en el sistema.
- [x] Debe registrar los campos de fecha creación y fecha modificación de forma automatica, oculata del usuario.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de Desarrollo

**Comment by fabianbarreto02** [comment]
El desarrollo del formulacio se realiza en el repositorio de campus_cliente en la rama [oferta_academica](https://github.com/udistrital/campus_cliente/tree/oferta_academica).

**Comment by mafeave** [comment]
Se verifica el formulario desarrollado, se listan de forma correcta los eventos correspondientes a la inscripción para el periodo seleccionado.
