### ISSUE TITLE
Definir modelo de datos para la gestión de información familiar del aspirante

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/campus_cliente#200]
Se debe definir cual modelo de datos se debe utilizar para el manejo del de la gestion de información del aspirante, este modelo debe cumplir con los siguientes requerimientos:

- [x] Debe ser lo mas general posible para posible futuros cambios del sistema.
- [x] El modelo debe poder registrar todas las preguntas de la sección información familiar.
- [x] El modelo debe ser desarrollado en la herramienta pgmodeler.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de diseño.

**Comment by fabianbarreto02** [comment]
Se define el Siguiente modelo para la gestión de información familiar del asperirante.

![Informacion_socioeconomica](https://user-images.githubusercontent.com/43799065/62328535-06d25180-b479-11e9-8066-aa93f6d3987d.png)

**Comment by fabianbarreto02** [comment]
se anexa el dbm.
[informacion_familiar.dbm.zip](https://github.com/udistrital/campus_cliente/files/3458705/informacion_familiar.dbm.zip)

**Comment by fabianbarreto02** [comment]
Se espera revisión por parte de @jairolh y @fnrojash.

**Comment by mafeave** [comment]
De acuerdo a la reunión realizada el día 2 de Agosto de 2019 con @jairolh se dan las siguientes observaciones:
- Relacionar el tipo_rol y la persona en la tabla de familiar, con lo anterior ya no sería necesaria la tabla relacion_persona_informacion_familiar.
- Dejar las tablas de tipo_metadato_pregunta y valor_metadato en un esquema nuevo del Core, nombre que se propone: Cuestionario.
- Agregar el campo de activo en la tabla de familiar
- Cambiar nombre de campo ocuapacion_id por ocupacion_id
- Cambiar nombre de campo nivel_de_educacion_id por nivel_educacion_id
- Cambiar nombre de la tabla tipo_metadato_pregnta por tipo_metadato_pregunta

Tener en cuenta que en el campo form_definition se debe definir:
- Si la pregunta es requerida 
- El formato del campo (numérico, texto, etc)

Para el desarrollo, en caso de que se cambie el nombre de una pregunta, considerar que no hayan registros que la relacionen para no alterar los resultados obtenidos en los reportes, siempre en caso de modificación, inactivar el registro mediante el campo de activo.

**Comment by fabianbarreto02** [comment]
Se relizan ajustes de acuerdo  a la reunión realizada el día 2 de Agosto de 2019 con @jairolh

![Informacion_socioeconomicaV2](https://user-images.githubusercontent.com/43799065/62387537-751e1f00-b520-11e9-9a7a-ed9bf3c454da.png)

**Comment by fabianbarreto02** [comment]
Se anexa el dbm.

[Informacion_socioeconomicaV2.dbm.zip](https://github.com/udistrital/campus_cliente/files/3462331/Informacion_socioeconomicaV2.dbm.zip)

**Comment by mafeave** [comment]
Se verifica la corrección de los ajustes solicitados.

**Comment by jairolh** [comment]
Se verifica la corrección de los ajustes solicitados.

**Comment by nodier25** [comment]
Recomiendo cambiar el nombre del campo valor por valoración

**Comment by fabianbarreto02** [comment]
Se Inicia el proceso de cambio del nombre como sugerencia por parte de @nodier25

**Comment by fabianbarreto02** [comment]
Se realiza el ajuste del cambio del nombre.

![Captura de Pantalla 2019-08-16 a la(s) 10 42 00 a  m](https://user-images.githubusercontent.com/43799065/63179789-86802480-c012-11e9-813c-4a7fd4cfa277.png)

**Comment by mafeave** [comment]
Modelo ajustado de acuerdo a sugerencias de @nodier25

**Comment by mafeave** [comment]
Por observaciones de reunión con los DBAs y Arquitectos ajustar el nombre del campo de valoracion de la tabla valor_metadato por respuesta

**Comment by fabianbarreto02** [comment]
Se realiza el ajuste sugerido en la reunion 

![Captura de Pantalla 2019-08-22 a la(s) 10 17 39 a  m](https://user-images.githubusercontent.com/43799065/63527144-2b44ab00-c4c6-11e9-8a9c-8dc2e2546fbb.png)

**Comment by fabianbarreto02** [comment]
Se espera revisión por parte de @jairolh y @fnrojash  para aprobación del modelo
