### ISSUE TITLE
remplazo de ramas principales y actualizacion de dorne para despliegue del cliente

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/campus_cliente#216]
se requiere remplazar las ramas principales para el despliegue del cliente, adicionalmente se recomienda esa [la plantilla actualizada de dorne para los clientes](https://github.com/udistrital/plan_adquisiciones_cliente/blob/master/.drone.yml) teniendo encuentra que se debe de cambiar la versión de nodejs para evitar errores de compilación

**Comment by jevilla94** [comment]
@BOTOOM @planesticud @miguerpe @neconoe 
Cordial saludo

Se ha realizado la copia del repositorio de Planestic-UD en la rama develop https://github.com/udistrital/campus_cliente/commit/b117f50f6341c384aa8b867a1554235f17e5e0d7, se realizó merge en la rama master https://github.com/udistrital/campus_cliente/commit/ddf236f84c859d68e9c0539510f3754215fbc67f y adicionalmente se ha restaruado la rama gh-pages para la visualización de la documentación que genera el angular.
